### PR TITLE
Update Contour CRDs

### PR DESCRIPTION
**Pull request by youngnick**
Signed-off-by: Nick Young <ynick@vmware.com>

### CODE REVIEW

**Review by stevesloka — APPROVED** [review]

**Comment by skriss** [comment]
This is still failing codegen, not sure why all the line wrap changes to operator.yaml

**Comment by sunjayBhatia** [comment]
> This is still failing codegen, not sure why all the line wrap changes to operator.yaml

Maybe old versions of tools?

**Comment by youngnick** [comment]
I think that was it, kustomize version was different on my machine. Sigh.

**Comment by youngnick** [comment]
Okay, I'm going to merge this one using admin powers since it's just the codecov check failing. This should clear up the scheduled CI failures.

**Pull request merged**
