### PR TITLE
Bump Envoy to v1.21.0

### PR DESCRIPTION
**Pull request by sunjayBhatia**

### CODE REVIEW

**Review by skriss — APPROVED** [review]
Really poor test coverage on this one :trollface: 

idk what's wrong with our codecov config that's causing the reports to look like this.

**Comment by sunjayBhatia** [comment]
> Really poor test coverage on this one :trollface:
> 
> idk what's wrong with our codecov config that's causing the reports to look like this.

huh, some of the tests that contribute to coverage are the ones that use the controller-runtime test manager etc. (https://github.com/projectcontour/contour-operator/blob/main/internal/operator/operator_test.go), they seem to pass but maybe some variability in what parts of the controller logic gets hit? I'm pretty confused though on this one since its across so many files, all reduced coverage

**Comment by skriss** [comment]
> > Really poor test coverage on this one :trollface:
> > idk what's wrong with our codecov config that's causing the reports to look like this.
> 
> huh, some of the tests that contribute to coverage are the ones that use the controller-runtime test manager etc. (https://github.com/projectcontour/contour-operator/blob/main/internal/operator/operator_test.go), they seem to pass but maybe some variability in what parts of the controller logic gets hit? I'm pretty confused though on this one since its across so many files, all reduced coverage

It almost seems like it's diffing against some old version of the operator, but I'm not sure.

**Comment by sunjayBhatia** [comment]
will open an issue on coverage, something to investigate

**Pull request merged**
