### PR TITLE
Creates project scaffolding

### PR DESCRIPTION
**Pull request by danehans**
Creates project scaffolding based on [kubernetes-template-project](https://github.com/kubernetes/kubernetes-template-project).

@jpeach I included you as an owner and a security point of contact. Let me know if any modifications are needed.

/cc @Miciah

### CODE REVIEW

**Comment by jpeach** [comment]
@danehans Every repo in the projectcontour org inherits the documents in https://github.com/projectcontour/.github, though they don't always show up in obvious ways in the GitHub UI. Other documents can be drawn from https://github.com/projectcontour/community.

**Comment by danehans** [comment]
> Every repo in the projectcontour org inherits the documents in https://github.com/projectcontour/.github

@jpeach thanks for the pointer, I've never worked with a [default community health file](https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file) before. It doesn't look like it's working though. For example, I tried creating an issue to see if the projectcontour/.github template works, but no-go. I also did not see the [contrib](https://github.com/projectcontour/.github/blob/master/CONTRIBUTING.md) when I submitted this PR.

**Comment by jpeach** [comment]
> > Every repo in the projectcontour org inherits the documents in https://github.com/projectcontour/.github
> 
> @jpeach thanks for the pointer, I've never worked with a [default community health file](https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file) before. It doesn't look like it's working though. For example, I tried creating an issue to see if the projectcontour/.github template works, but no-go. I also did not see the [contrib](https://github.com/projectcontour/.github/blob/master/CONTRIBUTING.md) when I submitted this PR.

It's working now; GitHub is weird :)

**Comment by jpeach** [comment]
Closed as a side-effect of renaming the default branch. Please re-post if there's anything left to do here.

**Pull request closed without merging**
