### PR TITLE
ci: run tests each hour

### PR DESCRIPTION
**Pull request by stevesloka**
Runs the tests hourly against `contour:main`. Will see if this works, then need to add some sort of notification mechanism. 

Signed-off-by: Steve Sloka <slokas@vmware.com>

### CODE REVIEW

**Comment by danehans** [comment]
Fixes: https://github.com/projectcontour/contour-operator/pull/206

**Comment by stevesloka** [comment]
I don't think this will run as a PR. Maybe we can just merge and then watch it?

**Review by sunjayBhatia — APPROVED** [review]

**Review by skriss — APPROVED** [review]

**Comment by skriss** [comment]
https://github.com/projectcontour/contour-operator/actions/runs/581991283

**Comment by danehans** [comment]
> ...then need to add some sort of notification mechanism.

xref: https://github.com/projectcontour/contour-operator/issues/235

**Pull request merged**
