### PR TITLE
Sets a 3-Minute Timeout for All e2e Wait Functions

### PR DESCRIPTION
**Pull request by danehans**
Many failed CI jobs are related to wait function timeouts. This PR sets a 3-Minute timeout for all e2e `waitX()` functions to reduce test flakes.

cc: @skriss 

Signed-off-by: Daneyon Hansen <daneyonhansen@gmail.com>

### CODE REVIEW

**Review by skriss — APPROVED** [review]
LGTM, thanks @danehans!

**Comment by skriss** [comment]
minor merge conflict to resolve since I merged #360

**Comment by danehans** [comment]
Commit `bb31741` resolves the merge conflict.

**Review by sunjayBhatia — APPROVED** [review]
only change i would make to this is maybe to make the timeout a little more descriptive, but its used in a variety of contexts so maybe not worh it

**Pull request merged**
