### PR TITLE
Running with UID 101 and GID 101 when using high ports

### PR DESCRIPTION
**Pull request by amdonov**
Our security team really hates us running any containers as root. Haven't done any testing on this, but it seems like it's reasonable to run envoy with an alternate UID when not attempting to bind to 80 and 443.

Interested in feedback both on behavior and approach. We're using the public envoy image, the default for the operator. Based upon a quick read it looks like the envoy user and group in that image has UID/GID of 101.

### CODE REVIEW

**Comment by danehans** [comment]
xref: https://github.com/projectcontour/contour-operator/issues/112

**Comment by amdonov** [comment]
Don't know how I missed that existing ticket. If you want to allow users to set security context parameters as part of the CRD, I'll implement it that way. Was trying to improve security without requiring additional configuration.

**Comment by youngnick** [comment]
I agree that this being configurable in the CRD would be ideal, we can default to 65534 - I think that it's better to default to nonroot, and need to change to use low ports.

**Comment by amdonov** [comment]
@dmorgan81 is implementing the suggested approach in #398

**Pull request closed without merging**
