### PR TITLE
Updates Gofmt to Cover e2e Tests

### PR DESCRIPTION
**Pull request by danehans**
Updates `fmt` Make target to cover e2e tests.

xref: https://github.com/projectcontour/contour-operator/pull/269

Signed-off-by: Daneyon Hansen <daneyonhansen@gmail.com>

### CODE REVIEW

**Review by skriss — APPROVED** [review]
LGTM. Not totally clear on why test/e2e isn't being picked up by the existing command, maybe due to build tags?

**Comment by sunjayBhatia** [comment]
> LGTM. Not totally clear on why test/e2e isn't being picked up by the existing command, maybe due to build tags?

Yeah I think that is probably why golangci-lint isn't picking it up, I bet https://github.com/projectcontour/contour-operator/pull/275 won't fail on the `test/e2e` change

**Comment by skriss** [comment]
> > LGTM. Not totally clear on why test/e2e isn't being picked up by the existing command, maybe due to build tags?
> 
> Yeah I think that is probably why golangci-lint isn't picking it up, I bet #275 won't fail on the `test/e2e` change

I tested this locally and it looked like it works when the path is explicitly specified, 🤷‍♂️

**Comment by sunjayBhatia** [comment]
> > > LGTM. Not totally clear on why test/e2e isn't being picked up by the existing command, maybe due to build tags?
> > 
> > 
> > Yeah I think that is probably why golangci-lint isn't picking it up, I bet #275 won't fail on the `test/e2e` change
> 
> I tested this locally and it looked like it works when the path is explicitly specified, 🤷‍♂️

Yeah this run didn't fail: https://github.com/projectcontour/contour-operator/pull/275/checks?check_run_id=2176583612

Had to run this locally to get legit errors: `./hack/golangci-lint.sh run --build-tags=e2e`

**Review by sunjayBhatia — APPROVED** [review]
LGTM but we still need to fix the code linting CI job to catch these sorts of things, this change is not sufficient to prevent unformatted code from being checked in

**Comment by sunjayBhatia** [comment]
> LGTM but we still need to fix the code linting CI job to catch these sorts of things, this change is not sufficient to prevent unformatted code from being checked in

I can do a quick PR to fix that @skriss unless youre already working on it

**Comment by skriss** [comment]
go for it, haven't started that

**Pull request merged**
