### PR TITLE
internal/operator: consolidate setting log fields

### PR DESCRIPTION
**Pull request by skriss**
Where applicable, instantiates local loggers that have structured
log fields pre-set and then reuses them throughout.

Signed-off-by: Steve Kriss <krisss@vmware.com>

### CODE REVIEW

**Comment by skriss** [comment]
The goal here is just to make things a little more readable by reducing verbosity.

**Review by youngnick — APPROVED** [review]
LGTM, seems more readable, and is a better match with `projectcontour/contour` style.

**Review by sunjayBhatia — APPROVED** [review]

**Comment by danehans** [comment]
Needs rebase, otherwise /lgtm.

**Comment by skriss** [comment]
I'll maybe hold off on rebasing this until after a few of @danehans's PRs have gone in, to avoid creating a bunch of rebase pain for him.

**Comment by skriss** [comment]
I took this a little further with #288, closing this one.

**Pull request closed without merging**
