### PR TITLE
CI: run e2e tests against all supported Kubernetes versions

### LINKED ISSUE #323: Operator should run e2e tests against latest kubernetes version N to N-2
In order to fulfill the guarantees we have set in our compatibility matrix https://projectcontour.io/resources/compatibility-matrix/

The Contour controller does so here: https://github.com/projectcontour/contour/blob/d9a0d5128dcfc67239b0c748c553d4b4c0957732/.github/workflows/prbuild.yaml#L11-L38

### PR DESCRIPTION
**Pull request by skriss**
Closes #323.

Signed-off-by: Steve Kriss <krisss@vmware.com>

### CODE REVIEW

**Review by sunjayBhatia — APPROVED** [review]

**Comment by skriss** [comment]
Having trouble getting all the jobs to pass at the same time, we may need to do some more flake-fighting here.

**Comment by danehans** [comment]
The operator upgrade test is failing with “found error message in operator contour-operator/contour-operator logs”. I'm going to try locally reproducing and I created https://github.com/projectcontour/contour-operator/issues/338 for tracking the need to capture the operator logs.

**Comment by danehans** [comment]
@skriss It appears CI is failing for this PR due to https://github.com/projectcontour/contour-operator/issues/341.

**Comment by danehans** [comment]
@skriss do you know why the `test-e2e-linux` and `test-example-linux` CI jobs are reporting "Waiting for status to be reported"?

**Comment by skriss** [comment]
> @skriss do you know why the `test-e2e-linux` and `test-example-linux` CI jobs are reporting "Waiting for status to be reported"?

Yeah, each of those have now been replaced by the three matrix jobs (e.g. test-e2e-linux (kubernetes:latest), test-e2e-linux (kubernetes:n-1), ...), but the original non-matrix jobs are still marked as required. Once we're happy with this PR, I'll update the branch protection rules to require the matrix jobs and not require the old jobs.

**Review by danehans — APPROVED** [review]

**Comment by danehans** [comment]
@skriss this PR has 2 approvals but I'll let you merge as I don't fully understand the steps for changing the branch protection rules.

**Comment by skriss** [comment]
OK, I'm going to get this in now and other PRs will have to update.

**Pull request merged**
