### PR TITLE
Enable the status subresource.

### LINKED ISSUE #32: Status Subresource
**Please describe the problem you have**
Enable the status subresource for the `contour` API:
```
// +kubebuilder:subresource:status
```

### PR DESCRIPTION
**Pull request by jpeach**
This fixes #32.

Signed-off-by: James Peach <jpeach@vmware.com>

### CODE REVIEW

**Comment by danehans** [comment]
@jpeach I'd like to bump my kubebuilder to v0.3.0 and test before tagging this PR. Otherwise, feel free to remove the kubebuilder bump and resubmit.

**Comment by jpeach** [comment]
> @jpeach I'd like to bump my kubebuilder to v0.3.0 and test before tagging this PR. Otherwise, feel free to remove the kubebuilder bump and resubmit.

I removed the kubebuilder version.

**Review by skriss — APPROVED** [review]
LGTM

**Review by stevesloka — APPROVED** [review]
/lgtm

**Pull request merged**
