### PR TITLE
sync CRDs from projectcontour/contour

### PR DESCRIPTION
**Pull request by skriss**
Signed-off-by: Steve Kriss <krisss@vmware.com>

### CODE REVIEW

**Comment by skriss** [comment]
Hmm, not sure why this is still showing a CRD error when running envtest-based tests, but not when running in kind clusters..

**Comment by skriss** [comment]
In light of #574, I opted to just disable the envtest-based tests rather than mucking around with kubebuilder versions/etc. since the tests are likely pretty redundant with E2E's anyway

**Comment by sunjayBhatia** [comment]
could the issue be a tools version? envtest etc. is probably pretty out of date here and on my dev machine currently

cool with dropping the tests since yeah we're planning on stopping supporting this anyways (and code hasn't changed tbh)

**Comment by skriss** [comment]
> could the issue be a tools version? envtest etc. is probably pretty out of date here and on my dev machine currently
> 
> cool with dropping the tests since yeah we're planning on stopping supporting this anyways (and code hasn't changed tbh)

Yeah my best guess is it's due to an old envtest/associated binaries, but updating to kubebuilder v3 to get newer versions is not super-straightforward and I didn't see the point of going down that road. I think as long as we have the E2E's working we still have decent confidence here.

**Review by sunjayBhatia — APPROVED** [review]

**Pull request merged**
