### PR TITLE
Adds Contour ConfigMap Support

### PR DESCRIPTION
**Pull request by danehans**
Adds support for managing Contour's ConfigMap.

Fixes https://github.com/projectcontour/contour-operator/issues/38

@jpeach @skriss @stevesloka @Miciah PTAL

### CODE REVIEW

**Comment by jpeach** [comment]
I don't think the template is the right approach here. Contour should expose a package with the Go struct for the config file, and we can consume that directly here.

**Comment by jpeach** [comment]
xref https://github.com/projectcontour/contour/issues/2621

**Comment by stevesloka** [comment]
The alternative would be to move the the CRD approach suggested here (https://github.com/projectcontour/contour/issues/2924#issuecomment-695081070), but is not built out just yet.

**Comment by danehans** [comment]
@jpeach is it possible to proceed with this approach since this is what's implemented today? I can create an issue that xrefs https://github.com/projectcontour/contour/issues/2621 and https://github.com/projectcontour/contour/issues/2924#issuecomment-695081070 and update the contour-operator when these projectcontour/contour issues are resolved.

**Comment by stevesloka** [comment]
@danehans I think this is fine to move forward with. The CRD swap is a lot more work and will require a deprecation window that shouldn't hold up this project. =)

**Comment by danehans** [comment]
@stevesloka I've updated the PR based, PTAL.

/cc @jpeach @Miciah

**Review by jpeach — APPROVED** [review]

**Pull request merged**
